DATASET:
  NAME: CIFAR10
  NUM_CLASSES: 10
  ROOT: ~/zzp/resnext/ResNeXt.pytorch/DATASETS/cifar.python
SOLVER:
  BASE_LR: 0.005
  LR_MILESTONES: [120, 240]
  MAX_EPOCHS: 300
  TRAIN_BATCH_SIZE: 128
  WARMUP: True
  WARMUP_EPOCH: 10
  WARMUP_FACTOR: 0.1
ISON:
  TRANS_FUN: 'bottleneck_transform'
  DEPTH: 29 
  ORTHO_COEFF: 1e-4
  HAS_BN: False
  HAS_ST: False
  SReLU: True